apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-app
  template:
    metadata:
      labels:
        app: cart-app
    spec:
      containers:
      - name: cart-app
        image: ram1uj/cart-app:latest
        ports:
        - containerPort: 8080