apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-app
  template:
    metadata:
      labels:
        app: product-app
    spec:
      containers:
      - name: product-app
        image: ram1uj/product-app:latest
        ports:
        - containerPort: 8080