name: 'ecom-app'
networks:
  app-network:

services:
  cart-service:
    image: ram1uj/cart-app
    ports:
      - "8100-8105:80"
    environment:
      SERVER_PORT: 80
    networks:
      - app-network

  product-service:
    image: ram1uj/product-app
    ports:
      - "8200-8210:8080"
    networks:
      - app-network



